import { z } from "zod";
import { listResponseSchema } from "@/lib/schemas/listResponse";

/** <input type="date"> returns "YYYY-MM-DD" */
const DateInputString = z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/, "Invalid date format (YYYY-MM-DD)");

export const GenderEnum = z.enum(["MALE", "FEMALE"]);
export type Gender = z.infer<typeof GenderEnum>;

/**
 * Create: studentCode is generated by backend (do NOT include here)
 */
export const StudentCreateDto = z.object({
    studentId: z.string().min(1),
    firstName: z.string().min(1),
    lastName: z.string().min(1),
    gender: GenderEnum,
    dateOfBirth: DateInputString.optional(),
    grade: z.string().min(1),
    section: z.string().min(1),
    parentName: z.string().optional(),
    parentPhone: z.string().optional(),
    address: z.string().optional(),
});
export type StudentCreateInput = z.infer<typeof StudentCreateDto>;

/**
 * Update: allow partial, but prevent empty update payload.
 * (If you WANT to allow empty updates, remove the .refine part.)
 */
export const StudentUpdateDto = StudentCreateDto.partial().refine(
    (v) => Object.keys(v).length > 0,
    { message: "At least one field is required" }
);
export type StudentUpdateInput = z.infer<typeof StudentUpdateDto>;

/** Response models (runtime safety) */
export const Student = z.object({
    id: z.string(),

    // ✅ generated by backend (STU-YYYY-000123)
    studentCode: z.string(),

    // school internal/legacy id (still stored & editable)
    studentId: z.string(),

    firstName: z.string(),
    lastName: z.string(),
    gender: GenderEnum,
    dateOfBirth: z.string().optional(),
    grade: z.string(),
    section: z.string(),
    parentName: z.string().optional(),
    parentPhone: z.string().optional(),
    address: z.string().optional(),
    createdAt: z.string().optional(),
});
export type Student = z.infer<typeof Student>;

export const ListStudentsResponse = listResponseSchema(Student);
export type ListStudentsResponse = z.infer<typeof ListStudentsResponse>;
