import type { SchoolRole } from "../types/jwt";

export type SuperAdminRole = "SUPER_ADMIN";

export const schoolPermissionMatrix = {
    "auth.me": ["SCHOOL_ADMIN", "TEACHER", "ACCOUNTANT"],
    "auth.changePassword": ["SCHOOL_ADMIN", "TEACHER", "ACCOUNTANT"],
    "students.create": ["SCHOOL_ADMIN", "ACCOUNTANT"],
    "students.list": ["SCHOOL_ADMIN", "TEACHER", "ACCOUNTANT"],
    "students.read": ["SCHOOL_ADMIN", "TEACHER", "ACCOUNTANT"],
    "students.update": ["SCHOOL_ADMIN", "ACCOUNTANT"],
    "students.delete": ["SCHOOL_ADMIN", "ACCOUNTANT"],
    "users.list": ["SCHOOL_ADMIN", "ACCOUNTANT", "TEACHER"],
    "users.create": ["SCHOOL_ADMIN", "ACCOUNTANT"],
    "users.update": ["SCHOOL_ADMIN", "ACCOUNTANT"],
    "users.resetPassword": ["SCHOOL_ADMIN", "ACCOUNTANT"],
    "users.delete": ["SCHOOL_ADMIN", "ACCOUNTANT"],
    "academicYears.list": ["SCHOOL_ADMIN", "ACCOUNTANT", "TEACHER"],
    "academicYears.read": ["SCHOOL_ADMIN", "ACCOUNTANT", "TEACHER"],
    "academicYears.create": ["SCHOOL_ADMIN", "ACCOUNTANT"],
    "academicYears.update": ["SCHOOL_ADMIN", "ACCOUNTANT"],
    "academicYears.setCurrent": ["SCHOOL_ADMIN", "ACCOUNTANT"],
    "academicYears.delete": ["SCHOOL_ADMIN", "ACCOUNTANT"],
    "classes.list": ["SCHOOL_ADMIN", "ACCOUNTANT", "TEACHER"],
    "classes.read": ["SCHOOL_ADMIN", "ACCOUNTANT", "TEACHER"],
    "classes.create": ["SCHOOL_ADMIN", "ACCOUNTANT"],
    "classes.update": ["SCHOOL_ADMIN", "ACCOUNTANT"],
    "classes.delete": ["SCHOOL_ADMIN", "ACCOUNTANT"],
    "sections.list": ["SCHOOL_ADMIN", "ACCOUNTANT", "TEACHER"],
    "sections.read": ["SCHOOL_ADMIN", "ACCOUNTANT", "TEACHER"],
    "sections.create": ["SCHOOL_ADMIN", "ACCOUNTANT"],
    "sections.update": ["SCHOOL_ADMIN", "ACCOUNTANT"],
    "sections.delete": ["SCHOOL_ADMIN", "ACCOUNTANT"],
    "enrollments.list": ["SCHOOL_ADMIN", "ACCOUNTANT", "TEACHER"],
    "enrollments.history": ["SCHOOL_ADMIN", "ACCOUNTANT", "TEACHER"],
    "enrollments.assign": ["SCHOOL_ADMIN"],
    "enrollments.transfer": ["SCHOOL_ADMIN"],
    "enrollments.promote": ["SCHOOL_ADMIN"],
    "enrollments.withdraw": ["SCHOOL_ADMIN"],
    "enrollments.audit.list": ["SCHOOL_ADMIN", "ACCOUNTANT"],
} as const satisfies Record<string, readonly SchoolRole[]>;

export const superAdminPermissionMatrix = {
    "superAdmin.me": ["SUPER_ADMIN"],
    "superAdmin.tenants.create": ["SUPER_ADMIN"],
    "superAdmin.tenants.list": ["SUPER_ADMIN"],
    "superAdmin.tenants.resetPassword": ["SUPER_ADMIN"],
    "superAdmin.users.list": ["SUPER_ADMIN"],
    "superAdmin.users.create": ["SUPER_ADMIN"],
    "superAdmin.users.update": ["SUPER_ADMIN"],
    "superAdmin.users.resetPassword": ["SUPER_ADMIN"],
} as const satisfies Record<string, readonly SuperAdminRole[]>;

export type SchoolPermission = keyof typeof schoolPermissionMatrix;
export type SuperAdminPermission = keyof typeof superAdminPermissionMatrix;

export const routePermissionMatrix = {
    "POST /auth/login": null,
    "POST /auth/refresh": null,
    "POST /auth/logout": null,
    "GET /auth/me": "auth.me",
    "POST /auth/change-password": "auth.changePassword",
    "POST /students": "students.create",
    "GET /students": "students.list",
    "GET /students/:id": "students.read",
    "PATCH /students/:id": "students.update",
    "DELETE /students/:id": "students.delete",
    "GET /users": "users.list",
    "POST /users": "users.create",
    "PATCH /users/:id": "users.update",
    "POST /users/:id/reset-password": "users.resetPassword",
    "DELETE /users/:id": "users.delete",
    "GET /academic-years": "academicYears.list",
    "GET /academic-years/:id": "academicYears.read",
    "POST /academic-years": "academicYears.create",
    "PATCH /academic-years/:id": "academicYears.update",
    "POST /academic-years/:id/set-current": "academicYears.setCurrent",
    "DELETE /academic-years/:id": "academicYears.delete",
    "GET /classes": "classes.list",
    "GET /classes/:id": "classes.read",
    "POST /classes": "classes.create",
    "PATCH /classes/:id": "classes.update",
    "DELETE /classes/:id": "classes.delete",
    "GET /sections": "sections.list",
    "GET /sections/:id": "sections.read",
    "POST /sections": "sections.create",
    "PATCH /sections/:id": "sections.update",
    "DELETE /sections/:id": "sections.delete",
    "GET /api/school/enrollments": "enrollments.list",
    "GET /api/school/enrollments/student/:studentId/history": "enrollments.history",
    "POST /api/school/enrollments/assign": "enrollments.assign",
    "POST /api/school/enrollments/transfer": "enrollments.transfer",
    "POST /api/school/enrollments/promote": "enrollments.promote",
    "POST /api/school/enrollments/withdraw": "enrollments.withdraw",
    "GET /api/school/enrollments/audit": "enrollments.audit.list",
    "POST /super-admin/login": null,
    "POST /super-admin/refresh": null,
    "POST /super-admin/logout": null,
    "GET /super-admin/me": "superAdmin.me",
    "POST /super-admin/tenants": "superAdmin.tenants.create",
    "GET /super-admin/tenants": "superAdmin.tenants.list",
    "POST /super-admin/tenants/:tenantId/reset-password": "superAdmin.tenants.resetPassword",
    "GET /super-admin/users": "superAdmin.users.list",
    "POST /super-admin/users": "superAdmin.users.create",
    "PATCH /super-admin/users/:id": "superAdmin.users.update",
    "POST /super-admin/users/:id/reset-password": "superAdmin.users.resetPassword",
} as const;
