"use client"

import { useMemo, useState, useCallback } from "react"
import {
    StudentCreateInputSchema,
    type StudentCreateInput,
    type StudentDto,
    type StudentGender,
} from "../api/students.dto"

import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Separator } from "@/components/ui/separator"
import { Badge } from "@/components/ui/badge"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { AlertTriangle } from "lucide-react"

type Props = {
    open: boolean
    onOpenChange: (v: boolean) => void
    title: string
    submitLabel: string
    initial?: Partial<StudentDto>
    submitting?: boolean
    error?: string | null
    academicYearOptions?: Array<{ id: string; name: string; code: string }>
    classOptions?: Array<{ id: string; name: string; code: string; academicYearId: string }>
    sectionOptions?: Array<{ id: string; name: string; code: string; classId: string }>
    strictPlacementRequired?: boolean
    onSubmit: (input: StudentCreateInput) => Promise<void> | void
}

const GenderValues: StudentGender[] = ["MALE", "FEMALE"]

type StudentFormState = {
    studentId: string;
    firstName: string;
    lastName: string;
    gender: StudentGender;
    dateOfBirth: string;
    grade: string;
    section: string;
    academicYearId: string;
    classId: string;
    sectionId: string;
    parentName: string;
    parentPhone: string;
    address: string;
};

function formStateFromInitial(initial?: Partial<StudentDto>): StudentFormState {
    return {
        studentId: initial?.studentId ?? "",
        firstName: initial?.firstName ?? "",
        lastName: initial?.lastName ?? "",
        gender: (initial?.gender as StudentGender) ?? "MALE",
        dateOfBirth: initial?.dateOfBirth ? initial.dateOfBirth.slice(0, 10) : "",
        grade: initial?.grade ?? "",
        section: initial?.section ?? "",
        academicYearId: initial?.academicYearId ?? "NONE",
        classId: initial?.classId ?? "NONE",
        sectionId: initial?.sectionId ?? "NONE",
        parentName: initial?.parentName ?? "",
        parentPhone: initial?.parentPhone ?? "",
        address: initial?.address ?? "",
    };
}

export function StudentFormDialog({
    open,
    onOpenChange,
    title,
    submitLabel,
    initial,
    submitting,
    error,
    academicYearOptions = [],
    classOptions = [],
    sectionOptions = [],
    strictPlacementRequired = false,
    onSubmit,
}: Props) {
    const [form, setForm] = useState<StudentFormState>(() => formStateFromInitial(initial))

    const filteredClasses = useMemo(() => {
        if (form.academicYearId === "NONE") return [];
        return classOptions.filter((item) => item.academicYearId === form.academicYearId);
    }, [classOptions, form.academicYearId]);

    const filteredSections = useMemo(() => {
        if (form.classId === "NONE") return [];
        return sectionOptions.filter((item) => item.classId === form.classId);
    }, [sectionOptions, form.classId]);

    const selectedSection = useMemo(
        () => filteredSections.find((item) => item.id === form.sectionId),
        [filteredSections, form.sectionId]
    );

    const resolvedSectionLabel = selectedSection?.name?.trim() || form.section.trim();

    const payload = useMemo(
        () => ({
            // studentCode is generated by backend
            studentId: form.studentId.trim(),
            firstName: form.firstName.trim(),
            lastName: form.lastName.trim(),
            gender: form.gender,
            dateOfBirth: form.dateOfBirth ? form.dateOfBirth : undefined,
            grade: form.grade.trim(),
            section: resolvedSectionLabel,
            academicYearId: form.academicYearId === "NONE" ? undefined : form.academicYearId,
            classId: form.classId === "NONE" ? undefined : form.classId,
            sectionId: form.sectionId === "NONE" ? undefined : form.sectionId,
            parentName: form.parentName.trim() || undefined,
            parentPhone: form.parentPhone.trim() || undefined,
            address: form.address.trim() || undefined,
        }),
        [form, resolvedSectionLabel]
    )

    const placementComplete =
        form.academicYearId !== "NONE" &&
        form.classId !== "NONE" &&
        form.sectionId !== "NONE";

    const canSubmit = useMemo(() => {
        const baseValid = StudentCreateInputSchema.safeParse(payload).success;
        if (!baseValid || submitting) return false;
        if (strictPlacementRequired && !placementComplete) return false;
        return true;
    }, [payload, strictPlacementRequired, placementComplete, submitting])

    const handleSubmit = useCallback(async () => {
        const parsed = StudentCreateInputSchema.safeParse(payload)
        if (!parsed.success) return
        await onSubmit(parsed.data)
    }, [payload, onSubmit])

    return (
        <Dialog
            open={open}
            onOpenChange={onOpenChange}
        >
            <DialogContent className="sm:max-w-2xl">
                <DialogHeader className="space-y-2">
                    <div className="flex items-center justify-between gap-3">
                        <DialogTitle className="text-lg">{title}</DialogTitle>
                        <Badge variant="secondary" className="bg-muted/40 text-muted-foreground">
                            Student
                        </Badge>
                    </div>
                    <p className="text-sm text-muted-foreground">
                        Enter the student’s personal details and academic info. Parent info is optional.
                    </p>
                </DialogHeader>

                <div className="space-y-6">
                    <section className="space-y-4">
                        <div className="text-sm font-medium">Student information</div>
                        <div className="grid gap-4 sm:grid-cols-2">
                            <div className="space-y-2">
                                <Label>Student ID (School)</Label>
                                <Input
                                    value={form.studentId}
                                    onChange={(e) => setForm((prev) => ({ ...prev, studentId: e.target.value }))}
                                    placeholder="Optional: leave blank to auto-use generated STU code"
                                />
                                <p className="text-xs text-muted-foreground">
                                    System always generates a code like <span className="font-mono">STU-2026-000123</span>. If this field is empty, Student ID will use that generated code.
                                </p>
                            </div>

                            <div className="space-y-2">
                                <Label>Gender</Label>
                                <Select value={form.gender} onValueChange={(v) => setForm((prev) => ({ ...prev, gender: v as StudentGender }))}>
                                    <SelectTrigger>
                                        <SelectValue placeholder="Select gender" />
                                    </SelectTrigger>
                                    <SelectContent>
                                        {GenderValues.map((g) => (
                                            <SelectItem key={g} value={g}>
                                                {g}
                                            </SelectItem>
                                        ))}
                                    </SelectContent>
                                </Select>
                            </div>

                            <div className="space-y-2">
                                <Label>First name</Label>
                                <Input value={form.firstName} onChange={(e) => setForm((prev) => ({ ...prev, firstName: e.target.value }))} placeholder="First name" />
                            </div>

                            <div className="space-y-2">
                                <Label>Last name</Label>
                                <Input value={form.lastName} onChange={(e) => setForm((prev) => ({ ...prev, lastName: e.target.value }))} placeholder="Last name" />
                            </div>

                            <div className="space-y-2">
                                <Label>Date of birth</Label>
                                <Input type="date" value={form.dateOfBirth} onChange={(e) => setForm((prev) => ({ ...prev, dateOfBirth: e.target.value }))} />
                            </div>
                        </div>
                    </section>

                    <Separator />

                    <section className="space-y-4">
                        <div className="text-sm font-medium">Academic</div>
                        <div className="grid gap-4 sm:grid-cols-2">
                            <div className="space-y-2">
                                <Label>Grade</Label>
                                <Input value={form.grade} onChange={(e) => setForm((prev) => ({ ...prev, grade: e.target.value }))} placeholder="e.g. Grade 6" />
                            </div>
                        </div>

                        <div className="grid gap-4 sm:grid-cols-3">
                            <div className="space-y-2">
                                <Label>Academic Year {strictPlacementRequired ? <span className="text-destructive">*</span> : <span className="text-muted-foreground">(Optional)</span>}</Label>
                                <Select
                                    value={form.academicYearId}
                                    onValueChange={(value) => {
                                        setForm((prev) => ({
                                            ...prev,
                                            academicYearId: value,
                                            classId: "NONE",
                                            sectionId: "NONE",
                                        }));
                                    }}
                                >
                                    <SelectTrigger><SelectValue placeholder="Select academic year" /></SelectTrigger>
                                    <SelectContent>
                                        {!strictPlacementRequired ? <SelectItem value="NONE">None</SelectItem> : null}
                                        {academicYearOptions.map((item) => (
                                            <SelectItem key={item.id} value={item.id}>{item.name} ({item.code})</SelectItem>
                                        ))}
                                    </SelectContent>
                                </Select>
                                {academicYearOptions.length === 0 ? (
                                    <p className="text-xs text-muted-foreground">
                                        No academic years found in Settings.
                                    </p>
                                ) : null}
                            </div>

                            <div className="space-y-2">
                                <Label>Class {strictPlacementRequired ? <span className="text-destructive">*</span> : <span className="text-muted-foreground">(Optional)</span>}</Label>
                                <Select
                                    value={form.classId}
                                    onValueChange={(value) => {
                                        setForm((prev) => ({ ...prev, classId: value, sectionId: "NONE" }));
                                    }}
                                >
                                    <SelectTrigger><SelectValue placeholder="Select class" /></SelectTrigger>
                                    <SelectContent>
                                        {!strictPlacementRequired ? <SelectItem value="NONE">None</SelectItem> : null}
                                        {filteredClasses.map((item) => (
                                            <SelectItem key={item.id} value={item.id}>{item.name} ({item.code})</SelectItem>
                                        ))}
                                    </SelectContent>
                                </Select>
                                {form.academicYearId !== "NONE" && filteredClasses.length === 0 ? (
                                    <p className="text-xs text-muted-foreground">
                                        No classes found for selected academic year.
                                    </p>
                                ) : null}
                            </div>

                            <div className="space-y-2">
                                <Label>Section {strictPlacementRequired ? <span className="text-destructive">*</span> : <span className="text-muted-foreground">(Optional)</span>}</Label>
                                <Select value={form.sectionId} onValueChange={(value) => setForm((prev) => ({ ...prev, sectionId: value }))}>
                                    <SelectTrigger><SelectValue placeholder="Select section" /></SelectTrigger>
                                    <SelectContent>
                                        {!strictPlacementRequired ? <SelectItem value="NONE">None</SelectItem> : null}
                                        {filteredSections.map((item) => (
                                            <SelectItem key={item.id} value={item.id}>{item.name} ({item.code})</SelectItem>
                                        ))}
                                    </SelectContent>
                                </Select>
                                {form.classId !== "NONE" && filteredSections.length === 0 ? (
                                    <p className="text-xs text-muted-foreground">
                                        No sections found for selected class.
                                    </p>
                                ) : null}
                                {form.sectionId === "NONE" && !strictPlacementRequired ? (
                                    <div className="space-y-2">
                                        <Label className="text-xs text-muted-foreground">Section label (manual)</Label>
                                        <Input
                                            value={form.section}
                                            onChange={(e) => setForm((prev) => ({ ...prev, section: e.target.value }))}
                                            placeholder="e.g. A"
                                        />
                                    </div>
                                ) : null}
                            </div>
                        </div>
                        {strictPlacementRequired && !placementComplete ? (
                            <p className="text-xs text-destructive">
                                Academic Year, Class, and Section are required before saving.
                            </p>
                        ) : null}
                    </section>

                    <Separator />

                    <section className="space-y-4">
                        <div className="flex items-center justify-between">
                            <div className="text-sm font-medium">Parent / Guardian</div>
                            <span className="text-xs text-muted-foreground">Optional</span>
                        </div>

                        <div className="grid gap-4 sm:grid-cols-2">
                            <div className="space-y-2">
                                <Label>Parent name</Label>
                                <Input value={form.parentName} onChange={(e) => setForm((prev) => ({ ...prev, parentName: e.target.value }))} placeholder="Full name" />
                            </div>

                            <div className="space-y-2">
                                <Label>Parent phone</Label>
                                <Input
                                    value={form.parentPhone}
                                    onChange={(e) => setForm((prev) => ({ ...prev, parentPhone: e.target.value }))}
                                    placeholder="e.g. +855..."
                                />
                            </div>

                            <div className="space-y-2 sm:col-span-2">
                                <Label>Address</Label>
                                <Input value={form.address} onChange={(e) => setForm((prev) => ({ ...prev, address: e.target.value }))} placeholder="Street, city, province" />
                            </div>
                        </div>
                    </section>

                    {error ? (
                        <div className="flex items-start gap-3 rounded-xl bg-destructive/10 p-3 text-sm text-destructive ring-1 ring-destructive/20">
                            <AlertTriangle className="mt-0.5 h-4 w-4" />
                            <div className="min-w-0">
                                <div className="font-medium">Could not save</div>
                                <div className="text-destructive/90">{error}</div>
                            </div>
                        </div>
                    ) : null}
                </div>

                <DialogFooter className="gap-2">
                    <Button variant="outline" onClick={() => onOpenChange(false)} disabled={submitting}>
                        Cancel
                    </Button>
                    <Button onClick={handleSubmit} disabled={!canSubmit}>
                        {submitting ? "Saving..." : submitLabel}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    )
}
