"use client"

import { useEffect, useMemo, useState, useCallback } from "react"
import {
    StudentCreateInputSchema,
    type StudentCreateInput,
    type StudentDto,
    type StudentGender,
} from "../api/students.dto"

import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Separator } from "@/components/ui/separator"
import { Badge } from "@/components/ui/badge"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { AlertTriangle } from "lucide-react"

type Props = {
    open: boolean
    onOpenChange: (v: boolean) => void
    title: string
    submitLabel: string
    initial?: Partial<StudentDto>
    submitting?: boolean
    error?: string | null
    onSubmit: (input: StudentCreateInput) => Promise<void> | void
}

const GenderValues: StudentGender[] = ["MALE", "FEMALE"]

export function StudentFormDialog({
                                      open,
                                      onOpenChange,
                                      title,
                                      submitLabel,
                                      initial,
                                      submitting,
                                      error,
                                      onSubmit,
                                  }: Props) {
    const [studentId, setStudentId] = useState("")
    const [firstName, setFirstName] = useState("")
    const [lastName, setLastName] = useState("")
    const [gender, setGender] = useState<StudentGender>("MALE")
    const [dateOfBirth, setDateOfBirth] = useState("")
    const [grade, setGrade] = useState("")
    const [section, setSection] = useState("")
    const [parentName, setParentName] = useState("")
    const [parentPhone, setParentPhone] = useState("")
    const [address, setAddress] = useState("")

    const resetForm = useCallback(() => {
        setStudentId("")
        setFirstName("")
        setLastName("")
        setGender("MALE")
        setDateOfBirth("")
        setGrade("")
        setSection("")
        setParentName("")
        setParentPhone("")
        setAddress("")
    }, [])

    // hydrate form when dialog opens; reset when closing
    useEffect(() => {
        if (!open) {
            resetForm()
            return
        }

        setStudentId(initial?.studentId ?? "")
        setFirstName(initial?.firstName ?? "")
        setLastName(initial?.lastName ?? "")
        setGender((initial?.gender as StudentGender) ?? "MALE")
        setDateOfBirth(initial?.dateOfBirth ? initial.dateOfBirth.slice(0, 10) : "")
        setGrade(initial?.grade ?? "")
        setSection(initial?.section ?? "")
        setParentName(initial?.parentName ?? "")
        setParentPhone(initial?.parentPhone ?? "")
        setAddress(initial?.address ?? "")
    }, [open, initial, resetForm])

    const payload = useMemo(
        () => ({
            // studentCode is generated by backend
            studentId: studentId.trim(),
            firstName: firstName.trim(),
            lastName: lastName.trim(),
            gender,
            dateOfBirth: dateOfBirth ? dateOfBirth : undefined,
            grade: grade.trim(),
            section: section.trim(),
            parentName: parentName.trim() || undefined,
            parentPhone: parentPhone.trim() || undefined,
            address: address.trim() || undefined,
        }),
        [studentId, firstName, lastName, gender, dateOfBirth, grade, section, parentName, parentPhone, address]
    )

    const canSubmit = useMemo(() => {
        return StudentCreateInputSchema.safeParse(payload).success && !submitting
    }, [payload, submitting])

    const handleSubmit = useCallback(async () => {
        const parsed = StudentCreateInputSchema.safeParse(payload)
        if (!parsed.success) return
        await onSubmit(parsed.data)
    }, [payload, onSubmit])

    return (
        <Dialog
            open={open}
            onOpenChange={(v) => {
                onOpenChange(v)
            }}
        >
            <DialogContent className="sm:max-w-2xl">
                <DialogHeader className="space-y-2">
                    <div className="flex items-center justify-between gap-3">
                        <DialogTitle className="text-lg">{title}</DialogTitle>
                        <Badge variant="secondary" className="bg-muted/40 text-muted-foreground">
                            Student
                        </Badge>
                    </div>
                    <p className="text-sm text-muted-foreground">
                        Enter the student’s personal details and academic info. Parent info is optional.
                    </p>
                </DialogHeader>

                <div className="space-y-6">
                    {/* Student info */}
                    <section className="space-y-4">
                        <div className="text-sm font-medium">Student information</div>
                        <div className="grid gap-4 sm:grid-cols-2">
                            <div className="space-y-2">
                                <Label>Student ID (School)</Label>
                                <Input
                                    value={studentId}
                                    onChange={(e) => setStudentId(e.target.value)}
                                    placeholder="Optional: school internal ID (not STU code)"
                                />
                                <p className="text-xs text-muted-foreground">
                                    System will generate a code like <span className="font-mono">STU-2026-000123</span>.
                                </p>
                            </div>

                            <div className="space-y-2">
                                <Label>Gender</Label>
                                <Select value={gender} onValueChange={(v) => setGender(v as StudentGender)}>
                                    <SelectTrigger>
                                        <SelectValue placeholder="Select gender" />
                                    </SelectTrigger>
                                    <SelectContent>
                                        {GenderValues.map((g) => (
                                            <SelectItem key={g} value={g}>
                                                {g}
                                            </SelectItem>
                                        ))}
                                    </SelectContent>
                                </Select>
                            </div>

                            <div className="space-y-2">
                                <Label>First name</Label>
                                <Input value={firstName} onChange={(e) => setFirstName(e.target.value)} placeholder="First name" />
                            </div>

                            <div className="space-y-2">
                                <Label>Last name</Label>
                                <Input value={lastName} onChange={(e) => setLastName(e.target.value)} placeholder="Last name" />
                            </div>

                            <div className="space-y-2">
                                <Label>Date of birth</Label>
                                <Input type="date" value={dateOfBirth} onChange={(e) => setDateOfBirth(e.target.value)} />
                            </div>
                        </div>
                    </section>

                    <Separator />

                    {/* Academic */}
                    <section className="space-y-4">
                        <div className="text-sm font-medium">Academic</div>
                        <div className="grid gap-4 sm:grid-cols-2">
                            <div className="space-y-2">
                                <Label>Grade</Label>
                                <Input value={grade} onChange={(e) => setGrade(e.target.value)} placeholder="e.g. Grade 6" />
                            </div>

                            <div className="space-y-2">
                                <Label>Section</Label>
                                <Input value={section} onChange={(e) => setSection(e.target.value)} placeholder="e.g. A" />
                            </div>
                        </div>
                    </section>

                    <Separator />

                    {/* Parent/Guardian */}
                    <section className="space-y-4">
                        <div className="flex items-center justify-between">
                            <div className="text-sm font-medium">Parent / Guardian</div>
                            <span className="text-xs text-muted-foreground">Optional</span>
                        </div>

                        <div className="grid gap-4 sm:grid-cols-2">
                            <div className="space-y-2">
                                <Label>Parent name</Label>
                                <Input value={parentName} onChange={(e) => setParentName(e.target.value)} placeholder="Full name" />
                            </div>

                            <div className="space-y-2">
                                <Label>Parent phone</Label>
                                <Input
                                    value={parentPhone}
                                    onChange={(e) => setParentPhone(e.target.value)}
                                    placeholder="e.g. +855..."
                                />
                            </div>

                            <div className="space-y-2 sm:col-span-2">
                                <Label>Address</Label>
                                <Input value={address} onChange={(e) => setAddress(e.target.value)} placeholder="Street, city, province" />
                            </div>
                        </div>
                    </section>

                    {/* Error */}
                    {error ? (
                        <div className="flex items-start gap-3 rounded-xl bg-destructive/10 p-3 text-sm text-destructive ring-1 ring-destructive/20">
                            <AlertTriangle className="mt-0.5 h-4 w-4" />
                            <div className="min-w-0">
                                <div className="font-medium">Could not save</div>
                                <div className="text-destructive/90">{error}</div>
                            </div>
                        </div>
                    ) : null}
                </div>

                <DialogFooter className="gap-2">
                    <Button variant="outline" onClick={() => onOpenChange(false)} disabled={submitting}>
                        Cancel
                    </Button>
                    <Button onClick={handleSubmit} disabled={!canSubmit}>
                        {submitting ? "Saving..." : submitLabel}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    )
}
